services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4_app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql_ci

  mysql_ci:
    image: mysql:8.0
    container_name: mysql_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: