services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - "8085:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:8
    container_name: mysql_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ci
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
